version: 2

sources:
  - name: bronze_f1
    database: bronze_f1_db
    schema: bronze_f1_db
    description: "Raw FastF1 ingested data."
    tables:
      - name: laps
      - name: telemetry
      - name: weather
      - name: messages
      - name: race_control_messages